- name: Create a Paloalto Firewall Tunnel
  hosts: all
  connection: local
  gather_facts: False
  environment:
    PYTHONHTTPSVERIFY: 0
    


  vars:
    server: 192.168.35.135
    

  #collections:
  #   - paloaltonetworks.panos

  #roles:
   #  - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Load Variables
    include_vars: vars1.yml
  
  - name: new var
    include_vars: vars4.yml

  - name: Configure Tunnel Interface
    panos_tunnel:
      provider: 
        ip_address: "{{ server }}"
        api_key: LUFRPT10MDFac2FzUjZxRUtXUW9oTWFlZzJOaHozSTg9eWNlTlVSSjZsY2pUV0l5a2xpcUhIRnk0eFREZE9zSDNWYkhDS2JKK09xbWN1TGNONkN1SFV5MFpDaE9WcTRrWQ==
      state: 'present'
      if_name: 'tunnel.3100'
      ip: '10.1.1.1/32'
      comment: 'Tunnel Interface for XYZ purpose'
      zone_name: 'inside'
      commit: False
    
        